### DISCUSSION TITLE
Can a property have multiple @pattern decorators?

### DISCUSSION THREAD

**Discussion by nkiesel** [microsoft/typespec#3019] [Q&A]
JSON schema allows to use `allOf` or `anyOf` for patterns, e.g.
```
lastName:
    type: string
    allOf:
      - pattern: ^[A-Za-z '-]{1,30}$
      - pattern: "[^ ]"
```
to limit the allowed characters, but also to make sure the value contains at least one non-blank character. How do I express this in typespec?
