### DISCUSSION TITLE
Is it possible to use examples for request body?

### DISCUSSION THREAD

**Discussion by dominikchrastek** [microsoft/typespec#4047] [Q&A]
Hello, is it possible to add multiple examples to request body?
I have following example:
[playground](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZb3BlbmFwaTMiOwoKdXNpbmcgVHlwZVNwZWMuSHR0cDsKCkBzZXJ2aWNlKHsKICB0aXRsZTogIk9DVE8gQVBJIMQqaWZpY2F0aW9uIiwKfSkKbmFtZXNwYWNlIMQmQXBpOwoKY29uc3QgQVZBSUxBQklMSVRZX0VYQU1QTEUgPSAjxFppZDogIjEyM8REOwptb2RlbCBBdmFpbGFiaWxpdHkgyCVzdHJpbmc7Cn0KCtMnQ2hlY2tTdWNjZXNzUmVzcG9uc2XFO0BzdGF0dXNDb2RlIMoLOiAyMDA7xB9ib2R5IMQFOs1QW13FaucAwNBpRGF0ZVJhbmdlQsQ%2B5wDKcHJvZHVjdEnkANE2YjkwM2Q0NC1kYzI0LTRjYTQtYWU3MS02YmRlNmM0ZjQ4NTQiLAogIG9w5AFBxTRERUZBVUxUxRdsb2NhbMRmU3RhcnQ6ICIyMDIyLTA1LeUBKcsgRW7EO8keOeYBR%2FgAuMwRSURz%2FwC%2B%2FwC%2B%2BgC%2BYcxnZHM6ICNb6wDBVDAwOsUDKzAxOjAwIl3mALNAZXhhbXBsZSj%2BAW4sICN76QKPxBogxRsgxBwiLCBkZXNjcmnlAJfTICB9Kdto8wEezW7PINZz1SXEePcCtMQg5gKpZG9jKCJUaGXoAYsgaWQuIinEGugAsv8BmecBmcQz6wHO6AM4zWPmAbnTYugBx8QW6gHe0UTlApcgZOQBX3RvIHF1ZXJ5IGZvciAoWVlZWS1NTS1ERCkuIFJlcXVpcmVkIGlmIGDsArNgIGlzIHNldNB%2B6wLmxBnuAwY%2F8wCIRW5k%2FwCG%2BACGxVP%2FAIjkA1DtAIhFbmT0AIZGaWx0ZXIgdGhlIHJlc3VsdHMgYnnFD2dpdmXkAWdzz2L%2BAxHEK%2B8DRMl35wSZQHRhZyjtAm0iKQpAcm91dGUoIi%2FMPSIpCmludGVyZuQFmssxaWVz5gJ4yDXmAKJwb3N0KMUKc3VtbWFyec5mIOUCtcYrb3BF5wDPCiAgIOQDKnJldHVybuQGSjrED%2B8FcCznBWgjW%2FQGEV0gfSwgfeQEP8VL6AN1x2MgMfEDassOIDEiIH0KICDkAJfxA2LmAJ7lBenGCv8Eaf8Eaf8EaeoD8d5s%2FwRt%2FwRt%2FwRtxXzyBtXpBHHkAWYp0xzvB0E7Cn0%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

I would expect the generated examples in openapi file will look like this:

```yaml
"requestBody":
  "content":
    "application/json":
    "schema":
      // skipped for simplicity
    "examples":
      "Date Range Body":
        "value":
          "productId": "6b903d44-dc24-4ca4-ae71-6bde6c4f4854"
          "optionId": "DEFAULT"
          "localDateStart": "2022-05-23"
          "localDateEnd": "2022-05-29"
      "AvailabilityIDs Body":
        "value":
          "productId": "6b903d44-dc24-4ca4-ae71-6bde6c4f4854"
          "optionId": "DEFAULT"
          "availabilityIds":
            - "2022-05-23T00:00:00+01:00"
```

Is it something that's not implemented yet or am I using the example decorator in a wrong way?
