### DISCUSSION TITLE
How to add decorators to items of an array?

### DISCUSSION THREAD

**Discussion by nonsocode** [microsoft/typespec#4454] [Q&A] [answered]
I can't find a way to apply decorators to items of an array.

I'm trying to achieve something like this. I'd like each string in the array to have a minimum length.

```
myObject:
  properties:
    sources:
      type: array
      items:
        type: string
        minLength: 3
```

I haven't been able to find a way to model this in typespec

```typespec
model MyObject {
  @minLength(3)
  sources: string[]
}
```
