### DISCUSSION TITLE
How to Decorate Parameters in Cookie?

### DISCUSSION THREAD

**Discussion by su8ru** [microsoft/typespec#4721] [OpenAPI3] [answered]
`@typespec/http` serves only `@header`, `@query` and `@path`. There are no decorators like `@cookie` to decorate the parameter is in the cookie.

I need an OpenAPI 3.0 output like this:
```yaml
      parameters:
        - name: some-cookie-name
          in: cookie
          required: true
          schema:
            type: string
```

Is there a way to define a parameter in the cookie?
