### ISSUE TITLE
Scalar not applying docs in sub scalars

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#1885]
[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=QGRvYygiQmFzZSBpZCBkb2MiKQpzY2FsYXIgbXlJZCBleHRlbmRzIHN0cmluZzsKCi8vIFRoaXPEKyBpcyBub3Qga2VwdArGSVVzZXLRSXVzZXLLS8RYOwo%3D)

```
@doc("Base id doc")
scalar myId extends string;

// This doc is not kept
@doc("User id doc")
scalar userId extends myId;

```

Produce
```yaml
components:
  schemas:
    myId:
      type: string
      description: Base id doc
    userId:
      type: string
      description: Base id doc
```

But expected `userId` schema to have `description: User id doc`

Same problem with `typespec-autorest`
