### ISSUE TITLE
ModelProperty reference and @encode don't work well

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#1968]
The encoding is lost
```tsp 
model Foo {
  id: int64;

  @encode("abc", string)
  ids: Foo.id;
}

```

makes 
```yaml
    Foo:
      type: object
      properties:
        id:
          type: integer
          format: int64
        ids:
          type: integer  # Should be string
          format: int64 # Should be abc
```
[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=bW9kZWwgRm9vIHsKICBpZDogaW50NjQ7CgogIEBlbmNvZGUoImFiYyIsIHN0cmluZynFJ3M6xDQuaWQ7Cn0K)
