### ISSUE TITLE
Model required fields are gone when using PATCH

### ISSUE THREAD

**Issue by dapuicon** [microsoft/typespec#2150]
We are getting problems when using `@patch` decorators on operations that use a model with required and optional fields. The required fields are gone on Schema generated by OpenAPI 3 emitter.

Example of the problem can be found on [this playground](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7DQoNCnVzaW5nIFR5cGVTcGVjLkh0dHDFGG1vZGVsIE9iamVjdCB7DQogIG5hbWU6IHN0cmluZzvEEXN1csQUP8sVfcQ7QHNlcnZpY2Uoe8YzInRlc3QifSkNCkByb3V0ZSgiL8QScyIpDQrEInNwYWNlIG1haW7GaUBwdXTECG9wIGdldChwYXlsb2FkOucAjSnICeUAhEBwYXRjaMcuxQzcMH0%3D&e=%40typespec%2Fopenapi3&options=%7B%7D).

-  Typespec definition
```tsp
import "@typespec/http";

using TypeSpec.Http;

model Object {
  name: string;
  surname?: string;
}

@service({name: "test"})
@route("/tests")
namespace main {
  @put
  op get(payload: Object): Object;
  @patch
  op patch(payload: Object): Object;
}
```

- Schemas generated
```yaml
components:
  schemas:
    Object:
      type: object
      properties:
        name:
          type: string
        surname:
          type: string
      required:
        - name
    ObjectUpdate:
      type: object
      properties:
        name:
          type: string
        surname:
          type: string
```
ObjectUpdate schema should have property **name** as **required**.
