### ISSUE TITLE
Want to get some clarities about character encoding in bytes

### ISSUE THREAD

**Issue by qiaozha** [microsoft/typespec#2204]
In https://github.com/microsoft/typespec/blob/main/packages/compiler/lib/decorators.tsp#L388-L400, there are two type of encoding in the `BytesKnownEncoding` enum. `base64` and `base64url`. I wonder if this is all kinds of encodings we will explicitly support in TypeSpec. There's a lot more different encodings as shown in here https://encoding.spec.whatwg.org/#names-and-labels 

I have already seen some logic about handling UInt8Array with `ascii`, `utf8`, `hex` encodings other than just base64 in the TypeScript Azure Core related libraries.   

Another question is, what is the default encoding for bytes ? 
If I have typespec like this 
```
model ByteTest {
  data: bytes
}
```
I will get a OpenAPI3 schema 
```yaml
    ByteTest:
      type: object
      properties:
        data:
          type: string
          format: byte
      required:
        - data
```
This result doesn't really tell us what is the default character encoding here. 

From the document about Buffer character encoding here https://nodejs.org/api/buffer.html#buffers-and-character-encodings, it says that if no encoding is specified, utf-8 will be used as default. I wonder if TypeSpec should provide such information to the downstream emitters ?
