### ISSUE TITLE
openapi3 for minValueExclusive and maxValueExclusive is invalid

### ISSUE THREAD

**Issue by mikekistler** [microsoft/typespec#2230]
The openapi3 emitter generates invalid output for `@minValueExclusive` and `@maxValueExclusive`. 

```yaml
components:
  schemas:
    Test:
      type: object
      properties:
        foo:
          type: number
          format: float
          exclusiveMinimum: 0
          exclusiveMaximum: 1
```

[Playground example](https://cadlplayground.z22.web.core.windows.net/?c=bW9kZWwgVGVzdCB7CiAgQG1heFZhbHVlRXhjbHVzaXZlKDEuMCnFGmluzxrFGGZvbz86IGZsb2F0MzI7Cn0%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

In OpenAPI v3 ([JSON Schema draft 5]), `exclusiveMinimum` and `exclusiveMaximum` are boolean values, not numbers.

> The value of "exclusiveMinimum" MUST be a boolean, representing whether the limit in "minimum" is exclusive or not

[JSON Schema draft 5]: https://datatracker.ietf.org/doc/html/draft-wright-json-schema-validation-00#section-5.5
