### ISSUE TITLE
openapi for model extends Record<unknown> is suboptimal

### ISSUE THREAD

**Issue by mikekistler** [microsoft/typespec#2247]
The OpenAPI produced by openapi3 and autorest emitters for a model that extends `Record<unknown>` contains redundant/unnecessary content.

[Playground example](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZb3BlbmFwaTMiOwp1c2luZyBPcGVuQVBJOwrHEFR5cGVTcGVjLkh0dHA7CkBzZXJ2aWNlKHsKICB0aXRsZTogIldpZGdldCBTxhsiLAogIHZlcnNpb246ICIxLjAuMCIsCn0pCm5hbWVzcGFjZSBEZW1vxy87Cgptb2RlbCBCYXIgZXh0ZW5kcyBSZWNvcmQ8dW5rbm93bj4gxG5iYXI%2FOiBzdHJpbmc7Cn0K&e=%40typespec%2Fopenapi3&options=%7B%7D)

The `allOf` in this schema is unnecessary and redundant with `additionalProperties: {}` on the main schema. A better rendering is:

```
    Bar:
      type: object
      properties:
        bar:
          type: string
      additionalProperties: {}
```

**Comment by timotheeguerin** [comment]
Also had this issue filed in typespec-azure repo for autorest https://github.com/Azure/typespec-azure/issues/3189

The thing is `extends` does get interpreted as `allOf` relation in openapi/swagger.

If you want Bar to have additional properties itself you can use `model Bar is Record<unknown` instead of `extends Record<unknown>`

I think we should make it however that teh `additionalProperties` doesn't show up on `Bar` itself either.

**Comment by mikekistler** [comment]
I should have tried `model Bar is Record<unknown>` -- it seems very promising. But alas it has its own problems.

This TypeSpec:
```typespec
model Bar is Record<unknown> {
  bar: string;
  baz: int32;
}
```

produces this schema
```yaml
    Bar:
      type: object
      additionalProperties: {}
```

which is not what we want, since `bar` and `baz` are simply lost.
