### ISSUE TITLE
[Bug?] Strip hyphen in @param doc

### ISSUE THREAD

**Issue by connorjs** [microsoft/typespec#2390]
### TL;DR

Strip the hyphen in `@param` doc comments.

### TSDoc spec

The TSDoc `@param` spec ([source](https://tsdoc.org/pages/tags/param/)) expects a hyphen.

> The `@param` tag is followed by a parameter name, followed by a hyphen, followed by a description.

### Current state

```
@route("/{personId}")
namespace person {
	/**
	 * Get a specific people resource.
	 *
	 * @param personId - Numeric ID of the person to get.
	 */
	op read(@path personId: int32): Person;
}
```

produces the following snippet with Open API emitter.

```yml
/people/{personId}:
  get:
    operationId: person_read
    description: Get a specific people resource.
    parameters:
      - name: personId
        in: path
        required: true
        description: '- Numeric ID of the person to get.'
        schema:
          type: integer
          format: int32
```

### Expected state

I expect the hyphen to be stripped, so the following (subset) instead.

```yml
      - name: personId
        description: 'Numeric ID of the person to get.'
```

### Other notes

I am happy to submit a PR for this, as I hope it’s straightforward. It could also be a good first PR for me as I encounter other documentation “issues” I would like to improve.
