### ISSUE TITLE
Unreachable types are resolved with `read` visibility

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2571]
Follow up from https://github.com/microsoft/typespec/issues/2517

```tsp
model Dog {
  @visibility("read") id: int32;
  @visibility("create", "update") secretName: string;
  name: string;
}
```
produce (missing `secretName`)
```yaml
components:
  schemas:
    Dog:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int32
          readOnly: true
        name:
          type: string
```
[Playground](https://cadlplayground.z22.web.core.windows.net/?c=bW9kZWwgRG9nIHsKICBAdmlzaWJpbGl0eSgicmVhZCIpIGlkOiBpbnQzMjvQIWNyZWF0ZSIsICJ1cGTECikgc2VjcmV0TmFtZTogc3RyaW5nxDZuzRB9Cg%3D%3D&e=@typespec/openapi3&options=%7B%7D) 

The problem with just changing the resolution from `Read` to all is that you endup with some case when the name is `DogReadOrCreateOrUpdateOrItem`, not sure if it is a bug or a design issue to how we decide to keep the suffixless name when using `Read`
