### ISSUE TITLE
how to specify the element type encoding of an array of scalar or a record of scalar ?

### ISSUE THREAD

**Issue by qiaozha** [microsoft/typespec#2572]
As title, I tried to define something like 
```
model Widget2 {
  @encode("binary")
  files: bytes[];
}
```
The openAPI3 generated output is like 
```yaml
    Widget2:
      type: object
      required:
        - files
      properties:
        files:
          type: array
          items:
            type: string
            format: byte
```
here the format should be binary if the encode decorators are being applied correctly ? 

I can work around this with a new scalar type like 
```
@encode("binary")
scalar B64Bytes extends bytes;

model Widget {
  files: B64Bytes[];
}
```
Similar issue exists in the other scalars with an encode decorator, see the example for utcDateTime [playground link](https://cadlplayground.z22.web.core.windows.net/?c=QGVuY29kZShEYXRlVGltZUtub3duRcQUaW5nLnJmYzcyMzEpCnNjYWxhciBNeVVUQyBleHRlbmRzIHV0Y8g3OwoKbW9kZWwgV2lkZ2V0IHsKICBmaWxlczrGNFtdOwogIGFub3RoZXJGxhlSZWNvcmQ8xSA%2BCn3OQjLFQ%2F8AnugAnsls6wCSxHLfQs1C9QCcy1A%2BOwp9&e=%40typespec%2Fopenapi3&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40typespec%2Fhttp%2Fall%22%5D%7D%7D)
