### ISSUE TITLE
can discriminator be optional ?

### ISSUE THREAD

**Issue by qiaozha** [microsoft/typespec#2710]
Not sure if it's a bug or intentional, in the below case, [public typespec playground link](https://cadlplayground.z22.web.core.windows.net/?c=QGRpc2NyaW1pbmF0b3IoImtpbmQiKQ0KbW9kZWwgUGV0IHsNCiAgbmFtZTogc3RyaW5nO8QRd2VpZ2h0PzogZmxvYXQzMjsNCn0%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)
```
@discriminator("kind")
model Pet {
  name: string;
  weight?: float32;
}
```
 the OpenAPI3 emitter output, will not put kind into required list
```yaml
    Pet:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        weight:
          type: number
          format: float
        kind:
          type: string
          description: Discriminator property for Pet.
      discriminator:
        propertyName: kind
```

However, in swagger emitter, it will put kind into the required list, see [azure playground link](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=QGRpc2NyaW1pbmF0b3IoImtpbmQiKQ0KbW9kZWwgUGV0IHsNCiAgbmFtZTogc3RyaW5nO8QRd2VpZ2h0PzogZmxvYXQzMjsNCn0%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D).  
But on the other hand, we also have test cases in cadl ranch to testify missing discriminator's case [cadl ranch link](https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/type/model/inheritance/nested-discriminator/main.tsp#L207).  

If it's intentional, I wonder why? if it's not, I am curious why we should allow discriminator decorator on a property that doesn't exist ?

/cc @xirzec
