### ISSUE TITLE
Openapi# emitter Handle bytes[] correctly in multipart #8

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2748]
Similiar issue for openapi3 emitter as for autorest 

https://github.com/Azure/typespec-azure/issues/8

```
op uploadImage(@header contentType: "multipart/form-data", @body image: MultiPartRequest): void;


model MultiPartRequest {
  document: bytes;  // Single document to translator
  glossary: bytes[];  // multiple glossary files
}
```
produce 
```yaml
        glossary:
          type: array
          items:
            type: string
            format: byte

```
[Playground](https://microsoft.github.io/typespec/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CnVzaW5nIFR5cGVTcGVjLkh0dHA7CgpAcm91dGUoImRvY3VtZW50OnRyYW5zbGF0ZSIpCm9wIHVwbG9hZEltYWdlKEBoZWFkZXIgY29udGVudMRLOiAibXVsdGlwYXJ0L2Zvcm0tZGF0YSIsIEBib2R5IGnEODogTcQjUGFydFJlcXVlc3QpOiB2b2lkOwoKCm1vZGVs0SEgewogIOkAkyBieXRlczsgIC8vIFNpbmdsZckcIHRvIOgAsm9yCiAgZ2xvc3NhcnnHNVtdxjfmAKVsZckgIGZpbGVzCn0KCg%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)
