### ISSUE TITLE
Doc structure reorganization 

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2781]
Proposal 
```yaml
Get started:
  installation:
  editor:
    vscode:
    vs:

Guides:
  Getting started with Typespec for Http:
  TypeSpec for OpenAPI:

Handbook:
  cli: (Cli usage)  styleGuide:
  formatter:
  reproducibility:
  configuration:

Language basics:
...rest of docs
```
