### ISSUE TITLE
Doc is lost when using union

### ISSUE THREAD

**Issue by lmazuel** [microsoft/typespec#2895]
Example:
```typescript
@doc("This is the doc")
union FooUnion {
  bar: "bar",
  "baz"
}

@doc("This is the doc")
enum FooEnum {
  bar: "bar",
  baz
}
```

will generate OpenAPI3:
```yaml
  schemas:
    FooEnum:
      type: string
      enum:
        - bar
        - baz
      description: This is the doc
    FooUnion:
      type: string
      enum:
        - bar
        - baz
```

Reproduce it on Swagger as well

Playground: https://typespec.io/playground?c=QGRvYygiVGhpcyBpcyB0aGUgZG9jIikKdW5pb24gRm9vVcUJewogIGJhcjogImJhciIsCiDECXoiCn0KCthCZW51bcRBRcQI0kBiYXoKfQo%3D&e=%40typespec%2Fopenapi3&options=%7B%7D
