### ISSUE TITLE
[Bug]: uint8 invalidly rendered in openapi3

### ISSUE THREAD

**Issue by lovebug356** [microsoft/typespec#3274]
### Describe the bug

According to the openapi documentation `uint8` is not existing in openapi specification see [link](https://swagger.io/docs/specification/data-models/data-types/).

The following TypeSpec
```
model Foo {
    bar: uint8;
}
```
is mapped as 
```
...
components:
  schemas:
    Foo:
      type: object
      required:
        - bar
      properties:
        bar:
          type: integer
          format: uint8
```
I would expect that it is mapped (as it is done in `json-schema`) to:
```
...
components:
  schemas:
    Foo:
      type: object
      required:
        - bar
      properties:
        bar:
          type: integer
          minimum: 0
          maximum: 255
```

### Reproduction

See [playground](https://typespec.io/playground?c=bW9kZWwgRm9vIHsKICBiYXI6IHVpbnQ4Owp9&e=%40typespec%2Fopenapi3&options=%7B%7D)

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
