### ISSUE TITLE
[Bug]: @doc on bytes doesn't output OpenAPI description

### ISSUE THREAD

**Issue by maxbeatty** [microsoft/typespec#3457]
### Describe the bug

If a `@doc` decorator is used on a `bytes` field, the resulting OpenAPI spec does not include a `description` for that field.

```
model UploadParameters {
  @doc("A `.zip` archive file.") 
  file: bytes,
}
```

```
components:
  schemas:
    UploadParametersMultiPart:
      type: object
      required:
        - file
      properties:
        file:
          type: string
          format: binary
```

If `file` is changed to `string`, then a `description` appears as expected:

```
model UploadParameters {
  @doc("A `.zip` archive file.") 
  file: string,
}
```

```
components:
  schemas:
    UploadParametersMultiPart:
      type: object
      required:
        - file
      properties:
        file:
          type: string
          description: A `.zip` archive file.
```

Other types like `int16`, `duration`, and `unknown` also work as expected.

### Reproduction

[Playground](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZb3BlbmFwaTMiOwoKdXNpbmcgVHlwZVNwZWMuSHR0cDvQFVJlc3Q7Cgptb2RlbCBVcGxvYWRlZEZpbGUgewogIEBtaW5MZW5ndGgoMSkKICBmaWxlTmFtZTogc3RyaW5nOwp9zjxQYXJhbWV0ZXJzxkBkb2MoIkEgYC56aXBgIGFyY2hpdmXFRy4iKSDHUjogYnl0ZXMsxE1pbnRlcmZhY2UgQVBJxkRzdW1tYXJ5KCLGYyBhbiBhdHRhY2htZW50IuQAl0Byb3V0ZSgiL3DGD3Bvc3QKICB17gCTKAogICAgQGhlYWRlciBjb250ZW505AEJOiAibXVsdGlwYXJ0L2Zvcm0tZGF0YSIsxjD%2BAMPrAMAKICApOuUAs%2BQAtXRhdHVzQ29kZSDKCzogMjAwO8YhYm9keesAyDrtAX3EJH07Cv8A%2FvAA%2Fm3zAP5N5AGd%2FwD6%2BAD65QCjcOkB0ugAo%2BoB5P8A8v8A8vIA8gp9&e=%40typespec%2Fopenapi3&options=%7B%7D)

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
