### ISSUE TITLE
[Bug]: JSON Schema emitter mismatched $ref when using a Record<T> type

### ISSUE THREAD

**Issue by xynydev** [microsoft/typespec#3498]
### Describe the bug

I am using [`Record<T>`](https://typespec.io/docs/language-basics/type-relations#recordt) to describe a datastructure that allows for arbitrary keys of a certain type.

When using the `@typespec/json-schema` emitter on such a Model, the generated jsonschema file splits the Record type into an entry in [`$defs`](https://json-schema.org/understanding-json-schema/structuring#defs). That Record type is, however, accessed using a [`$ref`](https://json-schema.org/understanding-json-schema/structuring#dollarref) pointing to a file called `RecordString.json` (which is not generated) instead of the correct subschema.

This issue causes any editor using the generated JSON Schema to complain and forgo validation and linting, so a quick fix would be appreciated.

### Reproduction

- [Playground link](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvanNvbi1zY2hlbWEiOwp1c2luZyBUeXBlU3BlYy5Kc29uU8UcOwoKQMQrxg4oKQptb2RlbCBNxAZOYW1lIHsKICAgIGFycmF5OiBBxAc8UmVjb3JkPHN0cmluZz4%2BCn0%3D&e=%40typespec%2Fjson-schema&options=%7B%7D)

Annotated reproduction below:
```tsp
// schema.tsp
import "@typespec/json-schema";
using TypeSpec.JsonSchema;

@jsonSchema()
model ModelName {
    array: Array<Record<string>>
}

// in YAML, this model could look like below:
//  array:
//     - anything-goes-here: "helo world :3"
//     - "custom key name": value
```
```sh
$ npx tsp compile ./schema.tsp 
TypeSpec compiler v0.56.0

Compilation completed successfully.
```
```yaml
# ModelName.yaml
# (actually generated as JSON, just using YAML for comment support)
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "ModelName.json",
    "type": "object",
    "properties": {
        "array": {
            "type": "array",
            "items": {
                "$ref": "RecordString.json"
				# this $ref does not exist, the correct way to reference the subschema below would be
				# "$ref": "#/$defs/RecordString"
            }
        }
    },
    "required": [
        "array"
    ],
    "$defs": {
        "RecordString": {
            "$schema": "https://json-schema.org/draft/2020-12/schema",
            "$id": "RecordString.json", # this ID being set does not help here
            "type": "object",
            "properties": {},
            "additionalProperties": {
                "type": "string"
            }
        }
    }
}
```

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
