### ISSUE TITLE
OpenAPI emitter: `@extension` should also be applied to `securitySchemes`

### ISSUE THREAD

**Issue by mcchrish** [microsoft/typespec#3555]
### Clear and concise description of the problem

```
@extension("x-amazon-apigateway-authtype", "custom")
model MyAuth is ApiKeyAuth<ApiKeyLocation.header, "Authorization">;
```

Should emit to:
```yaml
components:
  securitySchemes:
    MyAuth:
      type: apiKey
      in: header
      name: Authorization
      x-amazon-apigateway-authtype: custom
```

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://typespec.io/docs/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by markcowl** [comment]
est: 5

**Comment by thegagne** [comment]
Not sure if a separate issue, but I too would like to be able to use this for AWS API Gateway, and include the necessary things for using Cognito.

Similar to above but needs the authorizer as well:

```yaml
  securitySchemes:
    myCognitoSecurity:
      type: "apiKey"
      name: "Authorization"
      in: "header"
      x-amazon-apigateway-authtype: "cognito_user_pools"
      x-amazon-apigateway-authorizer:
        providerARNs:
        - "arn:aws:cognito-idp:us-west-2:<redacted>:userpool/us-west-2_<redacted>"
        type: "cognito_user_pools"
```

I believe this will also require changes to ApiKeyAuth to support scopes, as that section should look like:

```
      security:
      - myCognitoSecurity:
        - myScope
```
