### ISSUE TITLE
OpenAPI Emitter: `@example` doc tag should compile to `example` field

### ISSUE THREAD

**Issue by mcchrish** [microsoft/typespec#3602]
### Clear and concise description of the problem

```
/**
 * Uniform Resource Name
 * @example urn:xx:service::foobar/d9aadcde-a4b3-4fba-9f20-c5bd2fdb5071
 */
scalar URN extends string;
```

Should compile to
```yaml
    URN:
      type: string
      description: Uniform Resource Name
      example: urn:xx:service::foobar/d9aadcde-a4b3-4fba-9f20-c5bd2fdb5071
```

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://typespec.io/docs/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
