### ISSUE TITLE
[Bug]: leading zeros after dot are dropped in defaults

### ISSUE THREAD

**Issue by dfioravanti** [microsoft/typespec#3888]
### Describe the bug

If I define 
```
model Foo{
  bar?: float64 = 0.01 <- leading zero
}
```
it gets outputted as 
```
Foo:
  type: object
  properties:
    bar:
      type: number
      format: double
      default: 0.1 <- missing zero
```

meanwhile if I use anything but a zero after the dot it works. See the link to the playground

### Reproduction

[Playground Link](https://typespec.io/playground?c=bW9kZWwgRm9vewogIGJhcj86IGZsb2F0NjQgPSAwLjAxCn0KCsklMscmMs8nMTEKfQ%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
