### ISSUE TITLE
Operation example should resolve example for multiple responses correctly

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#4033]
[Playground Link](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwoKbW9kZWwgVXNlckZpZWxkcyB7CiAgbmFtZTogc3RyaW5nOwp9CgpAb3BFeGFtcGxlKAogICN7IHJldHVybsRNOsQPc3RhdHVzQ29kZTogMjAwLCB1c2VyOiAjWyN7x00iYWJjIiB9XSB9IH0sxkR0aXRsxBrHWiAxIiB9CinfbM5sNDA0LCBlcnJvcjogIk5vxXcgd2l0aCB0aGlzxXsi03JOb3QgZm91bmTGcm9wIGxpc3QoKTrlAP5AymLNbTIwMDvEH2JvZHlSb290xW466wE8W107Cn0gfCAoTm90RsRfUmVzcG9uc2UgJsVZ5wCp6QFYKTsK&e=%40typespec%2Fopenapi3&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40typespec%2Fhttp%2Fall%22%5D%7D%7D)

```tsp
import "@typespec/http";

using TypeSpec.Http;

model UserFields {
  name: string;
}

@opExample(
  #{ returnType: #{ statusCode: 200, user: #[#{ name: "abc" }] } },
  #{ title: "Example 1" }
)
@opExample(
  #{ returnType: #{ statusCode: 404, error: "No user with this name" } },
  #{ title: "Not found" }
)
op list(): {
  @statusCode statusCode: 200;
  @bodyRoot user: UserFields[];
} | (NotFoundResponse & {
  error: string;
});
```

Result in this both both responses
```yaml
examples:
                Not found:
                  summary: Not found
                  value: {}
                Example 1:
                  summary: Example 1
                  value: {}
```

There is 2 issues: 
1. the value are not actually populated
2. only the matching response should have the example
