### ISSUE TITLE
[Feature] Support variable-based nested config in tspconfig.yaml

### ISSUE THREAD

**Issue by dolauli** [microsoft/typespec#4305]
### Clear and concise description of the problem

**What is supported in now.**
```
  '@azure-tools/typespec-powershell':
    prefix: 'Az'
    service-name: Sphere
    module-name: "{prefix}.{service-name}
```
It works as expected. The tsp compiler could handle the variable well and parse it to:

```
  '@azure-tools/typespec-powershell':
    prefix: 'Az'
    service-name: Sphere
    module-name: "Az.Sphere"
```

**What is not supported now**

If there is a nested variable, it will not work.
```
  '@azure-tools/typespec-powershell':
    prefix: 'Az'
    service-name: Sphere
    metadata:
      authors: Microsoft Corporation
      owners: Microsoft Corporation
      description: "Microsoft Azure PowerShell: { service-name} cmdlets"
```

The tsp compiler will convert it as below with **{service-name}** not replaced by **Sphere**

```
  '@azure-tools/typespec-powershell':
    prefix: 'Az'
    service-name: Sphere
    metadata:
      authors: Microsoft Corporation
      owners: Microsoft Corporation
      description: "Microsoft Azure PowerShell: { service-name} cmdlets"
```

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://typespec.io/docs/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
