### ISSUE TITLE
 [OpenAPI3] `@example` decorator not supported for `union`s

### ISSUE THREAD

**Issue by RichardCPoint** [microsoft/typespec#4869]
### Describe the bug

The `@typespec/openapi3` emitter supports `@example`s for `model`s, but outputs incorrect examples for `union`s.

For example ([playground link](https://typespec.io/playground/?c=QGV4YW1wbGUoI3sgYTogMSB9KQptb2RlbCBBIHsKIMQUaW50ZWdlcjsKfQoK1C91bmlvbiBVxS9udW1iZXI6xQzMPSwKICB9xAV0ZXh0yB9zOiBzdHJpbmfHHn0K&e=%40typespec%2Fopenapi3&options=%7B%7D)):
```typespec
@example(#{ a: 1 })
union U {
  number: {
    a: integer,
  },
  text: {
    s: string,
  },
}
```

should output with `{ a: 1 }` as the example, but instead it is `{}`:
```yaml
    U:
      anyOf:
        - type: object
          properties:
            a:
              type: integer
          required:
            - a
        - type: object
          properties:
            s:
              type: string
          required:
            - s
      example: {}
```

(The TypeSpec compiler correctly detects any errors in the `@example` tag, e.g. using `@example(#{ a: "string" })` causes a compile error – so presumably the issue lies in the `@typespec/openapi3` package.)

### Reproduction

Playground link:
https://typespec.io/playground/?c=QGV4YW1wbGUoI3sgYTogMSB9KQptb2RlbCBBIHsKIMQUaW50ZWdlcjsKfQoK1C91bmlvbiBVxS9udW1iZXI6xQzMPSwKICB9xAV0ZXh0yB9zOiBzdHJpbmfHHn0K&e=%40typespec%2Fopenapi3&options=%7B%7D

Or example:
```typespec
@example(#{ a: 1 })
union U {
  number: {
    a: integer,
  },
  text: {
    s: string,
  },
}
```

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
