### ISSUE TITLE
openapi 3.1 - support tuples

### ISSUE THREAD

**Issue by chrisradek** [microsoft/typespec#5013]
Open API 3.1 supports defining tuples via Json Schema `prefixItems`.

Given the following TypeSpec:

```tsp
model Foo {
  tuple: [string, string];
}
```

We can emit an Open API 3.1 schema that looks like this:

```yaml
Foo:
  type: object
  properties:
    tuple:
      type: array
      prefixItems:
        - type: string
        - type: string
  required:
    - tuple
```

This matches what our json schema emitter currently emits.

For reference, our Open API 3.0 emitter does not support emitting tuples due to the lack of `prefixItems` and instead outputs this:

```yaml
Foo:
  type: object
  required:
    - tuple
  properties:
    tuple:
      type: array
      items: {}
```
