### ISSUE TITLE
Support `@param`, `@template`, `@prop` targetting identifiers that need escaping

### ISSUE THREAD

**Issue by edixon-github** [microsoft/typespec#5239]
## Summary of the problem 

Identifier for `@prop` `@param`, etc. in jsdoc respect the same identifier rule as typespec identifier minus the keywords.
This means you cannot target any property or parameter that needs to be escaped(except keywords)

[Playground showcasing problem](https://typespec.io/playground/?e=%40typespec%2Fopenapi3&c=LyoqCiAqIEBwcm9wIGEgywFXb3JrcyAxyh7wn5qA0SAyyiBtb2RlbM4eM8oeZm9vLWJhcsYeRG9lc24ndCB3b3JryiNGaXJzdCBuYW1l2SMxMjNhYmPHZNYjQHRlc3THItAjLwrmAKVUxCN7CiAgYTogc3RyaW5nOwog5QDhzBBgxS1gzRPnAMfOFeoAuc4Y5gCuzhTlAJ%2FLE30%3D&options=%7B%7D&vs=%7B%7D)

```tsp
/**
 * @prop a            Works 1
 * @prop 🚀           Works 2
 * @prop model        Works 3
 * @prop foo-bar      Doesn't work
 * @prop First name   Doesn't work
 * @prop 123abc       Doesn't work
 * @prop @test        Doesn't work
 */
model Test {
  a: string;
  🚀: string;
  `model`: string;
  `foo-bar`: string;
  `First name`: string;
  `123abc`: string;
  `@test`: string;
}
```

resolved doc in openapi3
```yaml
      properties:
        a:
          type: string
          description: Works 1
        🚀:
          type: string
          description: Works 2
        model:
          type: string
          description: Works 3
        foo-bar:
          type: string
        First name:
          type: string
        123abc:
          type: string
        '@test':
          type: string
```

## Design Approved

Follow the same escape logic as in typespec. Use ` to escape anything that is not an identifier(except keywords which don't apply in doc comments)

```tsp
/**
 * @prop a            Works 1
 * @prop 🚀           Works 2
 * @prop model        Works 3
 * @prop `foo-bar`    Works now!
 * @prop `First name` Works now!
 * @prop `123abc`     Works now!
 * @prop `@test`      Works now!
 */
model Test {
  a: string;
  🚀: string;
  `model`: string;
  `foo-bar`: string;
  `First name`: string;
  `123abc`: string;
  `@test`: string;
}
```

### Targetting nested property/parmaeters

While not part of this proposal this is compatible with a potential nested property reference 

```tsp
/**
 * @prop `nested-prop`.`123abc`            Works
 */
model Test {
 `nested-prop`: {
    `123abc`: string
  }
}
```

**Comment by timotheeguerin** [comment]
The problem is not ultimately just limited to `-` but the fact that identifier can be escaped to be any possible string but there isn't an equivalent for jsdoc.

Related issue with jsdoc https://github.com/jsdoc/jsdoc/issues/1468 as we have been trying to follow their syntax here we'll have to diverge to allow more.

An option is to reuse the same escape 

```tsp
/**
 * @param `foo-bar`
 * @param `@some`
 */
```

**Comment by timotheeguerin** [comment]
## Summary of the problem 

Identifier for `@prop` `@param`, etc. in jsdoc respect the same identifier rule as typespec identifier minus the keywords.
This means you cannot target any property or parameter that needs to be escaped(except keywords)

[Playground showcasing problem](https://typespec.io/playground/?e=%40typespec%2Fopenapi3&c=LyoqCiAqIEBwcm9wIGEgywFXb3JrcyAxyh7wn5qA0SAyyiBtb2RlbM4eM8oeZm9vLWJhcsYeRG9lc24ndCB3b3JryiNGaXJzdCBuYW1l2SMxMjNhYmPHZNYjQHRlc3THItAjLwrmAKVUxCN7CiAgYTogc3RyaW5nOwog5QDhzBBgxS1gzRPnAMfOFeoAuc4Y5gCuzhTlAJ%2FLE30%3D&options=%7B%7D&vs=%7B%7D)

```tsp
/**
 * @prop a            Works 1
 * @prop 🚀           Works 2
 * @prop model        Works 3
 * @prop foo-bar      Doesn't work
 * @prop First name   Doesn't work
 * @prop 123abc       Doesn't work
 * @prop @test        Doesn't work
 */
model Test {
  a: string;
  🚀: string;
  `model`: string;
  `foo-bar`: string;
  `First name`: string;
  `123abc`: string;
  `@test`: string;
}
```

resolved doc in openapi3
```yaml
      properties:
        a:
          type: string
          description: Works 1
        🚀:
          type: string
          description: Works 2
        model:
          type: string
          description: Works 3
        foo-bar:
          type: string
        First name:
          type: string
        123abc:
          type: string
        '@test':
          type: string
```

## Proposal

Follow the same escape logic as in typespec. Use ` to escape anything that is not an identifier(except keywords which don't apply in doc comments)

```tsp
/**
 * @prop a            Works 1
 * @prop 🚀           Works 2
 * @prop model        Works 3
 * @prop `foo-bar`    Works now!
 * @prop `First name` Works now!
 * @prop `123abc`     Works now!
 * @prop `@test`      Works now!
 */
model Test {
  a: string;
  🚀: string;
  `model`: string;
  `foo-bar`: string;
  `First name`: string;
  `123abc`: string;
  `@test`: string;
}
```


### Targetting nested property/parmaeters

While not part of this proposal this is compatible with a potential nested property reference 

```tsp
/**
 * @prop `nested-prop`.`123abc`            Works
 */
model Test {
 `nested-prop`: {
    `123abc`: string
  }
}
```
