### ISSUE TITLE
TypeSpec VSCode extension should not auto-regen the sdks in the vscode workspace

### ISSUE THREAD

**Issue by chunyu3** [microsoft/typespec#5319]
TypeSpec VSCode extension will auto-load all the configurations (tspConfig.yaml) in the workspace. And if there is `emit` configured in the tspConfig.yaml, the sdk will be re-generated.

```
emit:
  - "@azure-tools/typespec-ts"
options:
  "@azure-tools/typespec-ts":
    package-dir: "ai-vision-face-rest"
    generateMetadata: true
    generateTest: true
    packageDetails:
      name: "@azure-rest/ai-vision-face"
      description: "Face API REST Client"
```
expected.
TypeSpec VSCode should not auto-load tspConfig.yaml.
