### ISSUE TITLE
be able to set parameters as required in the client.tsp file

### ISSUE THREAD

**Issue by gracewilcox** [microsoft/typespec#5371]
### Clear and concise description of the problem

Hi! I need to be able to mark a parameter as required, but just for one language. 

Usually you do that by adding a question mark, but I want to be able to do it in the client.tsp file as a customization only for the language I'm working in.

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [docs](https://typespec.io/docs/).
- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by gracewilcox** [comment]
Hi! I'm converting a brownfield service to generate from typespec. I need to mark a parameter as required. Other languages can change things in their convenience layer, but I'm working in Go, and we don't have a convenience layer. I need the generated code to match exactly the generated code I had with autorest.

With autorest, it was pretty easy to mark it required:
```yaml
# make SASToken parameter required
  - from: swagger-document
    where: $.paths["/backup"].post.parameters[0]
    transform: $["required"] = true
```
But now with typespec I need to completely rewrite the method in the client.tsp to do the same thing.
