### ISSUE TITLE
[Bug]: Unable to use `{service-name}` interpolation for filenames with openapi3-emitter when only one service is defined

### ISSUE THREAD

**Issue by tmeckel** [microsoft/typespec#5866]
### Describe the bug

Due to the code in `packages/openapi3/src/openapi.ts`

```typescript
 function resolveOutputFile(service: Service, multipleService: boolean, version?: string): string {
    return interpolatePath(options.outputFile, {
      "openapi-version": specVersion,
      "service-name": multipleService ? getNamespaceFullName(service.type) : undefined,
      version,
    });
  }
```

the following emitter configuration does not work and always yields filenames without the defined service name, when only one (single) Service is compiled and emitted via OpenAPI3

```yaml
parameters:
  base-dir:
    default: "{cwd}"

output-dir: "{base-dir}/dist"

emit:
  - "@typespec/openapi3"

options:
  "@typespec/openapi3":
    emitter-output-dir: "{output-dir}"
    output-file: "{service-name}.{version}.{file-type}"
    file-type: yaml
```

Related: #1787

### Reproduction

1. Define a single **(!!)** versioned REST Service using TypeSpec in `main.tsp`.
2. Use the `output-file: "{service-name}.{version}.{file-type}"` option for the  `@typespec/openapi3` emitter
3. The filename will always be `1.0.0.yaml` (or `1.0.0.json`respectively).
4. Add an additional (dummy) Service to `main.tsp` or import a service defined in another `.tsp` file into `main.tsp`
5. Now the interpolation works as expected and the emitted filenames contain the service name as expected.

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
