### ISSUE TITLE
Extension: Generate from TypeSpec does not work with client.tsp as entrypoint file

### ISSUE THREAD

**Issue by swathipil** [microsoft/typespec#6062]
### Describe the bug

I've copied over the main.tsp and client.tsp from [[this](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/schemaregistry/SchemaRegistry)] folder into a test project following [these instructions](https://github.com/allenjzhang/typespec-e2e-demo/blob/main/doc/user-journey.md#references).

I tried to "Generate from TypeSpec" with the client.tsp and Python emitter specified, but it's still using main.tsp as the entrypoint file and the client.tsp changes are not being applied during Python client generation.

tspconfig.yaml:
```
parameters:
  "service-dir":
    default: "sdk/schemaregistry"
  "dependencies":
    "additionalDirectories": []
    default: ""
emit:
  - "@azure-tools/typespec-autorest"
  - "@typespec/http-client-python"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/data-plane"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "data-plane"
    emit-lro-options: "none"
    emitter-output-dir: "{project-root}/../"
    output-file: "data-plane/Microsoft.SchemaRegistry/{version-status}/{version}/sc\
      hemaregistry.json"
  "@typespec/http-client-python":
    package-dir: "azure-schemaregistry"
    package-name: "{package-dir}"
    emitter-output-dir: "{project-root}/azure-schemaregistry/_generated/"
    package-version: 1.3.0b4
    generate-packaging-files: false
    flavor: azure
    generate-test: true
    generate-sample: true
  "@azure-tools/typespec-python":
    package-dir: "azure-schemaregistry"
    package-name: "{package-dir}"
    emitter-output-dir: "{project-root}/azure-schemaregistry/_generated/"
    package-version: 1.3.0b4
    generate-packaging-files: false
    flavor: azure
    generate-test: true
    generate-sample: true
  "@azure-tools/typespec-java":
    package-dir: "azure-data-schemaregistry"
    namespace: com.azure.data.schemaregistry
    partial-update: true
    flavor: azure
  "@azure-tools/typespec-ts":
    package-dir: "schema-registry"
    generateMetadata: false
    generateTest: false
    packageDetails:
      name: "@azure/schema-registry"
    flavor: azure
  "@azure-tools/typespec-csharp":
    package-dir: "Azure.Data.SchemaRegistry"
    namespace: "{package-dir}"
    clear-output-folder: true
    model-namespace: true
    flavor: azure
```

### Reproduction

1. Add the main.tsp, client.tsp, tspconfig.yaml into the project.
2. ![Image](https://github.com/user-attachments/assets/a0ac4948-ef0f-4d94-9bea-3cbb9725447b)
3. ![Image](https://github.com/user-attachments/assets/786968ea-cef9-40d7-ae04-e5c10f1f384d)

I'm not sure if the entrypoint file needs to be set/change elsewhere in the config files. However, I believe it should automatically use the client.tsp file as the entrypoint file/apply those if I'm explicitly right-clicking on that file for generation.

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
