### ISSUE TITLE
[Bug]: @typespec/http-client-csharp crashes due to missing package-name in tspconfig.yaml

### ISSUE THREAD

**Issue by YukixPlanet** [microsoft/typespec#6212]
### Describe the bug

**Bug Description**
The emitter @typespec/http-client-csharp crashes during compilation when trying to generate a C# client.
The error message indicates that a required option package-name is missing in the configuration.

**Error Message**
Emitter "@typespec/http-client-csharp" crashed! This is a bug.
Please file an issue at https://github.com/Microsoft/typespec/issues

Error: Error: Failed to generate the library. Exit code: 1.
StackTrace:
Unable to parse required option package-name from configuration.
   at Microsoft.TypeSpec.Generator.Configuration.ReadRequiredStringOption(JsonElement root, String option) 
   at Microsoft.TypeSpec.Generator.Configuration.Load(String outputPath, String json) 
   at Microsoft.TypeSpec.Generator.PluginHandler.LoadPlugin(CommandLineOptions options) 
   at Microsoft.TypeSpec.Generator.GeneratorRunner.RunAsync(CommandLineOptions options) 
   at Microsoft.TypeSpec.Generator.Program.Run(CommandLineOptions options, GeneratorRunner runner)

**Steps to Reproduce**
1.Initialize a new TypeSpec project
  `tsp init`
2.Enable the C# client emitter in tspconfig.yaml
  emit:
  "@typespec/http-client-csharp": true
3.Run TypeSpec compilation
  tsp compile .
4.The following error appears:
  Unable to parse required option package-name from configuration.

**Temporary Workaround**
To avoid this error, I commented out @typespec/http-client-csharp in tspconfig.yaml, so it does not run during compilation:
emit:
  - "@typespec/openapi3"
  - // - "@typespec/http-client-csharp" 
  - "@typespec/http-server-csharp"

**Environment**
TypeSpec Compiler Version: 0.65.3
@typespec/http-client-csharp Version: 0.1.9-alpha.20250228.1
Node.js Version: 20.10.0
Operating System: Windows  11

### `tspconfig.yaml`
```yaml
emit:
  - "@typespec/openapi3"
  - "@typespec/http-client-csharp"
  - "@typespec/http-server-csharp"
options:
  "@typespec/openapi3":
    emitter-output-dir: "{output-dir}/schema"
  "@typespec/http-client-csharp":
    emitter-output-dir: "{output-dir}/clients/csharp"
  "@typespec/http-server-csharp":
    emitter-output-dir: "{output-dir}/server/generated"
```
### main.tsp

```tsp
import "@typespec/http";
import "@typespec/versioning"; 

using TypeSpec.Http;
using TypeSpec.Versioning; 

@server("https://api.weyi.com/v1", "正式環境")
@server("https://api.develop.com/v1", "測試環境")
@versioned(Versions)
namespace KMArticleSystem {
  enum Versions {
    v1;
    v2;
  }
```

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
