### ISSUE TITLE
Named Enum for OpenAPI 3.1

### ISSUE THREAD

**Issue by Downchuck** [microsoft/typespec#6419]
### Clear and concise description of the problem

OpenAPI 3.1 supports named enums with oneOf - consider the following named enum:

```
enum MY_ENUM {
  "NAME-A": "value-a",
  "NAME-B": "value-b",
}
```

We can now go from OpenAPI 3.0 (without extensions):

```
    MY_ENUM:
      type: string
      enum:
        - value-a
        - value-b
```

to OpenAPI 3.1 standard:

```
  type: string
  oneOf:
  - title: NAME-A
    const: value-a
  - title: NAME-B
    const: value-b
```
