### ISSUE TITLE
[Bug]: typespec/openapi3 doesn't support {version-status}

### ISSUE THREAD

**Issue by santiagxf** [microsoft/typespec#6456]
### Describe the bug

Microsoft organizes APIs in folders like `{service-namespace}/data-plane/{service-name}/{version-status}/{version}`. The following configuration for OpenAPI 3 emmiters won't work because `{version-status}` is not supported as a parameter, as opposite to other emmiters.

```yaml
  "@typespec/openapi3":
    emitter-output-dir: "{project-root}/.."
    output-file: "{output-folder-base}/{version-status}/{version}/openapi.yaml"
```

### Reproduction

```yaml
  "@typespec/openapi3":
    emitter-output-dir: "{project-root}/.."
    output-file: "{output-folder-base}/{version-status}/{version}/openapi.yaml"
```

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
