### ISSUE TITLE
multiple log levels in output panel

### ISSUE THREAD

**Issue by wanlwanl** [microsoft/typespec#6633]
### emit .net server

> 1. multiple log level here

```
2025-03-24 17:19:10.173 [error] [Warn]: Enum 'TodoItemStatus' must have either a summary or doc
2025-03-24 17:19:10.174 [error] [Warn]: Enum 'TodoItemPatchStatus' must have either a summary or doc
```

**Comment by chunyu3** [comment]
Hello @wanlwanl Have you enabled trace for csharp-server-emitter? This is log from csharp-server-emitter, and all the emitter log is trace log.

And it is not multiple log levels, `[Warn]` is not a log level, it is a text in the log message, the server-emitter log a message like `[Warn]: Enum 'TodoItemStatus' must have either a summary or doc`

**Comment by wanlwanl** [comment]
Hi @chunyu3, this is the tspconfig.yaml I used:
```
emit:
  - "@typespec/openapi3"
  - "@typespec/http-server-csharp"
  - "@typespec/http-client-csharp"
  - "@typespec/http-client-java"
  #  - "@typespec/http-server-javascript" # js server gen throws error: Error: Unimplemented: new form of multipart requests
  - "@typespec/http-client-python"
  - "@azure-tools/typespec-ts"
options:
  "@typespec/openapi3":
    emitter-output-dir: "{project-root}/../x/openapi3"
  "@typespec/http-client-csharp":
    emitter-output-dir: "{project-root}/../x/clients/dotnet"
  "@typespec/http-server-csharp":
    emitter-output-dir: "{project-root}/../x/servers/aspnet/generated"
  "@typespec/http-server-javascript":
    emitter-output-dir: "{project-root}/../x/servers/node/tsp-output/@typespec/http\
      -server-javascript"
    express: true
  "@typespec/http-client-java":
    emitter-output-dir: "{project-root}/../x/clients/java"
  "@typespec/http-client-python":
    emitter-output-dir: "{project-root}/../x/clients/python"
  "@azure-tools/typespec-ts":
    "emitter-output-dir": "{project-root}/../x/clients/javascript"
    packageDetails:
      name: "@notabrand/todo-non-branded"

```
