### ISSUE TITLE
[Bug]: Create and Update transforms emit original models in OpenAPI when specified in op parameters

### ISSUE THREAD

**Issue by abes-xpv** [microsoft/typespec#6917]
### Describe the bug

In the example below, `Update<A>` emits the expected OpenAPI schema for `UpA` but emits the full model as `UpdateA` when used inline as a parameter value. 

```typespec
model A {
  a: string;
  @visibility(Lifecycle.Create, Lifecycle.Read)
  b: string;
}

// UpA is correctly emitted with only the updateable properties of A
model UpA is Update<A>;

// UpdateA is incorrectly emitted with the all the properties of A
op updateOp(param: Update<A>): A;
```

### Reproduction

See [this Playground example](https://typespec.io/playground/?c=bW9kZWwgQSB7CiAgYTogc3RyaW5nOwogIEB2aXNpYmlsaXR5KExpZmVjeWNsZS5DcmVhdGUsIMoSUmVhZCkKICBiyj19CgovLyBVcEEgaXMgY29ycmVjdGx5IGVtaXR0ZWQgd2l0aCBvbmx5IHRoZSB1cGRhdGVhYmxlIHByb3BlcnRpZXMgb2YgQQrmAJzHSFXFKDxBPjvHXsQPxRppbtdkxF9hbGzFCNBcb3DHek9wKHBhcmFtOspiKTogQTsK&e=%40typespec%2Fopenapi3&options=%7B%7D)

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by abes-xpv** [comment]
This was working as expected in the 0.64.x release: https://typespec.io/playground/?c=bW9kZWwgQSB7CiAgYTogc3RyaW5nOwogIEB2aXNpYmlsaXR5KExpZmVjeWNsZS5DcmVhdGUsIMoSUmVhZCkKICBiyj19CgovLyBVcEEgaXMgY29ycmVjdGx5IGVtaXR0ZWQgd2l0aCBvbmx5IHRoZSB1cGRhdGVhYmxlIHByb3BlcnRpZXMgb2YgQQrmAJzHSFXFKDxBPjvHXsQPxRppbtdkxF9hbGzFCNBcb3DHek9wKHBhcmFtOspiKTogQTsK&e=%40typespec%2Fopenapi3&options=%7B%7D&version=0.64.x

**Comment by timotheeguerin** [comment]
I think this is due to how the openapi3 emitter tries to resolve the logical model when you do things like `op test(...A): void` 

As an alternative, you can insead just pass `A` and use `@parameterVisibility` to say that those parmaeters should usse the update visibility 

https://typespec.io/playground/?c=bW9kZWwgQSB7CiAgYTogc3RyaW5nOwogIEB2aXNpYmlsaXR5KExpZmVjeWNsZS5DcmVhdGUsIMoSUmVhZCkKICBiyj19CgovLyBVcEEgaXMgY29ycmVjdGx5IGVtaXR0ZWQgd2l0aCBvbmx5IHRoZSB1cGRhdGVhYmxlIHByb3BlcnRpZXMgb2YgQQrmAJzHSFXFKDxBPjvHXsQPxRppbtdkxF9hbGzFCNBcb3DHek9wKHBhcmFtOspiKTogQTsK&e=%40typespec%2Fopenapi3&options=%7B%7D

**Comment by abes-xpv** [comment]
Thanks @timotheeguerin. Specifying `@parameterVisibility` does resolve the problem but this is a fairly trivial example. I am still concerned that the TypeSpec source in the original post can produce an OpenAPI schema object that claims to be an `Update` transform but is not:
- The object name in the schema is `UpdateA`
- The `description` property describes it as an update transform
- But the schema still includes the `b` property that should not be visible in `Lifecycle.Update`

```yaml
    UpdateA:
      type: object
      required:
        - a
        - b
      properties:
        a:
          type: string
        b:
          type: string
      description: |-
        A copy of the input model `T` with only the properties that are visible during the
        "Update" resource lifecycle phase.

        The "Update" lifecycle phase is used for properties passed as parameters to operations
        that update data, like HTTP PATCH operations.

        This transformation will include only the properties that have the `Lifecycle.Update`
        visibility modifier, and the types of all properties will be replaced with the
        equivalent `CreateOrUpdate` transformation.

        If a `NameTemplate` is provided, the new model will be named according to the template.
        The template uses the same syntax as the `@friendlyName` decorator.
```

Here is another minimal example where the argument itself has properties with different visibility transformations that cannot be reconciled by `@parameterVisibility`:
https://typespec.io/playground/?c=bW9kZWwgQSB7CiAgYTogc3RyaW5nOwogIEB2aXNpYmlsaXR5KExpZmVjeWNsZS5DcmVhdGUsIMoSUmVhZCkKICBiyj19CgrGV0LFV2LfWM1G1UdvZHk8VSBleHRlbmRzIHt9LCBDyw4%2BxWZwYXJhbTrFCyAgdXBkYXRlOiBVxQg8VT7EeiAgY%2BUAvjog5gDGPEM%2BOyAKICB9xGpvcCBzb21lT3AoLi4uxXFBLCBCPik6IEE7Cg%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D&version=1.0.0-rc.0

In the above example both `UpdateA` and `CreateB` schema objects are emitted with names and descriptions that indicate the transforms were applied but both UpdateA and CreateB include properties that do not match the requested lifecycles.

The example above produces the expected OpenAPI schema in version 0.64: 
https://typespec.io/playground/?c=bW9kZWwgQSB7CiAgYTogc3RyaW5nOwogIEB2aXNpYmlsaXR5KExpZmVjeWNsZS5DcmVhdGUsIMoSUmVhZCkKICBiyj19CgrGV0LFV2LfWM1G1UdvZHk8VSBleHRlbmRzIHt9LCBDyw4%2BxWZwYXJhbTrFCyAgdXBkYXRlOiBVxQg8VT7EeiAgY%2BUAvjog5gDGPEM%2BOyAKICB9xGpvcCBzb21lT3AoLi4uxXFBLCBCPik6IEE7Cg%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D&version=0.64.x
