### ISSUE TITLE
[Bug]: Unable to get basic example to work

### ISSUE THREAD

**Issue by AndyWDev** [microsoft/typespec#7450]
### Describe the bug

I'm using TypeSpec v1.0.0 with npm 11.4.1 and .net 9 (visual studio 22  17.14.0).

Following the basic how to, I am unable to get a successful compile.

```
npm install -g @typespec/compiler@latest
mkdir bob
cd bob
tsp init              <-- rest api, C# server stubs
tsp compile .    <-- this works 
```

however, 

if after the tsp init, I change the tspconfig.yaml to the one in the example (code generation C#)

```
emit:
  - "@typespec/openapi3"
  - "@typespec/http-server-csharp"
options:
  "@typespec/openapi3":
    emitter-output-dir: "{output-dir}/schema"
    openapi-versions:
      - 3.1.0
  "@typespec/http-server-csharp":
    emitter-output-dir: "{output-dir}/server/generated"
```
It fails with 

error import-not-found: Couldn't resolve import "@typespec/http-server-csharp"

That is about as far as I can get.

### Reproduction

On a clean vm forllow the instructions on the C# Generation example

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
