### ISSUE TITLE
openapi3 - model extends Array generates invalid schema

### ISSUE THREAD

**Issue by chrisradek** [microsoft/typespec#7519]
[Playground link](https://typespec.io/playground/?c=bW9kZWwgQSBleHRlbmRzIEFycmF5PGludDMyPiB7fQ0KDQrGI0IgadMe&e=%40typespec%2Fopenapi3&options=%7B%7D)

When a TypeSpec model extends an array, the generated Open API schema is invalid. The schema has `type: object`, while the `allOf` subschema has `type: array`. These contradict.

__Example TypeSpec:__
```tsp
model A extends Array<int32> {}

model B is Array<int32> {}
```

__Expected Open API Schemas:__
```yml
components:
  schemas:
    A:
      type: array
      items:
        type: integer
        format: int32
    B:
      type: array
      items:
        type: integer
        format: int32
```

__Actual Open API Schemas:__
```yml
components:
  schemas:
    A:
      type: object
      allOf:
        - type: array
          items:
            type: integer
            format: int32
    B:
      type: array
      items:
        type: integer
        format: int32
```
