### ISSUE TITLE
[Bug]: Component names don't include namespace when the model is an array

### ISSUE THREAD

**Issue by cucho** [microsoft/typespec#7720]
### Describe the bug

Inside a namespace, array component names are not prefixed with the namespace.

### Reproduction

[Link to playground](https://typespec.io/playground/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CnVzaW5nIEh0dHA7CgpAc2VydmljZSgpCm5hbWVzcGFjZSBTdHVmZjsKCm9wIGNyZWF0ZURvY3VtZW50KCk6IEVudmVsb3BlLsgVOwrLO8geIHsKICBtb2RlbCDIKMUTICB0b3BpY3M6IFTFCDsKICB9CsksxhUgaXMgc3RyaW5nW107xB1zY2FsYXLGHiBleHRlbmTIIjsKfQ%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40typespec%2Fhttp%2Fall%22%5D%7D%7D)

Relevant part:

```
//...
namespace Envelope {
  //...
  model Topics is string[];

  scalar Topic extends string;
}
```

Expected OpenAPI 3.1 output:

```
//...
components:
  //...
    Envelope.Topic:
      type: string
    Envelope.Topics:
      type: array
      items:
        type: string
```

Got instead:

```
//...
components:
  //...
    Envelope.Topic:
      type: string
    Topics:
      type: array
      items:
        type: string
```

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
